version: '3'
services:
        node:
                build: backend
                ports: 
                - "8080:5000"
                volumes: 
                - ./backend:/usr/src/app
        react:
                build: frontend
                ports: 
                - "3000:3000"
